spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

#  sql:
#    init:
#      mode: always

  liquibase:
    enabled: true

logging:
  level:
    root:
      ERROR